spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.h2.Driver  #h2 드라이버 설정
    url: "jdbc:h2:tcp://localhost/~/test"
    username: sa
    password: ""
  jpa:
    properties:
      hibernate:
        format-sql: true
        ddl-auto: update
        dialect: org.hibernate.dialect.H2Dialect
    show_sql: true
    generate-ddl: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB
file:
  upload-dir: /Users/mac/Desktop/fileDB


