spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.h2.Driver  #h2 드라이버 설정
    url: "jdbc:h2:tcp://localhost/~/test"
    username: sa
    password: ""
#    url: "jdbc:mysql://localhost:3306/MY_DB?characterEncoding=UTF-8&serverTimezone=UTC"
#    username: "root"
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: "!gidrms1"
  jpa:
    properties:
      hibernate:
        format-sql: true
        ddl-auto: update
        dialect: org.hibernate.dialect.H2Dialect
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show_sql: true
    generate-ddl: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB
file:
  upload-dir: /Users/mac/Desktop/fileDB


